### ISSUE TITLE
[Question} - Bottom navigation

### ISSUE THREAD

**Issue by ArbenMaloku** [webfactorymk/flutter-template#34]
First of all, thanks for the template. I was wondering if there is a chance to provide us an example with BottomNavigation.

Already did something, but the main problem for me is navigating between tabs and showing correct state of the back button.

For example, when I navigate to "Home" tab, back button is visible. Should I use nested navigation per each tab?

Would be curious to hear from you .

Thanks again.
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-07-19 at 00 13 29](https://user-images.githubusercontent.com/12657320/126083701-dedfe1db-9ec3-4fcd-9bae-32316b38a9d3.png)

**Comment by dimitar-zabaznoski** [comment]
We will provide a bottom navigation bar eventually, but for now, we're busy working on other projects so we can't help you immediately. 

I'd use nested navigation per tab only if your tabs are very complex, otherwise, try to make the home router delegate work with your current tabs. Taking a deep dive into Nav 2.0 will greatly help you here.
